### PR TITLE
Orientation fixing

### PR DESCRIPTION
**Pull request by lojpa**

### CODE REVIEW

**Review by joanj94 — COMMENTED** [review]
How this prevents from losing data when a layout is recreated?

**Comment by lojpa** [comment]
With this code, after rotating screen the method onCreate() will not be called, so the data will stay at the field. I think i dont need to save them and if you think that i need to do this,i can do this but i think it is not necessary

**Comment by joanj94** [comment]
I think it's better so save the data using onSaveInstanceState and then recorver it on onCreate, maybe now we don't need it as it is, but it's a good practise to have it, just in case, like this you can have more control over the fields.

**Comment by lojpa** [comment]
Okay if you think that is necessary to implement this, i will implement.

**Pull request merged**
